// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  link_list: dynamic(() => import("./LinkList")),
  movie_banner: dynamic(() => import("./MovieBanner")),
  promotion: dynamic(() => import("./Promotion")),
  rich_text: dynamic(() => import("./RichText")),
  spotlight: dynamic(() => import("./Spotlight")),
};
